import type { Metadata } from "next";
import {Fjalla_One} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import NavBar from "@/app/navBar/NavBar";

const fjallaOne = Fjalla_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-fjalla-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${fjallaOne.className} ${fjallaOne.variable} antialiased`}
        suppressHydrationWarning={true}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
         <NavBar/>
          {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
